package swa

const(
	WIF_VERSION = 0x80
	WIF_COMPRESSED_FLAG = 0x01
	WALLET_ADDRESS_FLAG = 0x00

	PUBKEY_NOT_COMPRESSED_FLAG = 0x04
	PUBKEY_COMPRESSED_EVEN = 0x02
	PUBKEY_COMPRESSED_ODD = 0x03

	CHECKSUM_LEN = 4

	PRIVATE_KEY_KEN = 32
)